"""
This file is generated by sqldao-generator; don't modify anything.
If you need to do it, you should create another class.
"""
from sqlalchemy import Column, BigInteger, VARCHAR, Text, SmallInteger, Integer, Double, DateTime

from sqldaogenerator.entity.base import Base


class Sample(Base):
    __tablename__ = 't_sample'

    id = Column(BigInteger, autoincrement=True, primary_key=True, comment='主鍵')
    col_var = Column(VARCHAR, comment='字串')
    col_text = Column(Text, comment='長字串')
    col_tinyint = Column(SmallInteger, comment='微整數')
    col_int = Column(Integer, comment='整數')
    col_double = Column(Double, comment='浮點數')
    col_datetime = Column(DateTime, comment='時間')
