"""
This file is generated by sqldao-generator;
you can modify connection properties yourself.
"""
from sqlalchemy import create_engine

from sqldaogenerator.common.Database import Database


class Datasource(Database):

    def __init__(self):
        user = 'daniel'
        password = '0614'
        host = 'localhost'
        port = 3306
        dbname = 'database_test'
        connection_string = f"mysql+mysqlconnector://{user}:{password}@{host}:{port}/{dbname}"
        self.engine = create_engine(connection_string,
                                    echo=True,
                                    pool_recycle=270)
        super().__init__()


datasource = Datasource()
