"""This file is generated by sqldao-generator."""
from sample.dao.Datasource import datasource


class BaseDao:

    def __init__(self):
        self.engine = datasource.engine
        self.Session = datasource.Session
