"""This file is generated by sqldao-generator; you can modify connection properties yourself."""
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from sqldaogenerator.common.transaction_holder import register_session_maker


class Datasource:

    def __init__(self):
        user = 'daniel'
        password = '0614'
        host = 'localhost'
        port = 3306
        dbname = 'database_test'
        connection_string = f"mysql+mysqlconnector://{user}:{password}@{host}:{port}/{dbname}"
        self.engine = create_engine(connection_string, echo=True, pool_recycle=270)
        self.Session = sessionmaker(bind=self.engine)
        register_session_maker(self.Session)


datasource = Datasource()
