from sqlalchemy import Column, BigInteger, VARCHAR, Text, SmallInteger, Integer, Double, DateTime

from sqldaogenerator.entity.base import Base

"""This file is generated by sqldao-generator; don't modify anything. If you need to do it, you should create another class."""


class Sample(Base):
    __tablename__ = 't_sample'

    col_datetime = Column(DateTime, comment='時間')
    col_double = Column(Double, comment='浮點數')
    col_int = Column(Integer, comment='整數')
    col_text = Column(Text, comment='長字串')
    col_tinyint = Column(SmallInteger, comment='微整數')
    col_var = Column(VARCHAR, comment='字串')
    id = Column(BigInteger, autoincrement=True, primary_key=True, comment='主鍵')
