from dataclasses import dataclass
from datetime import datetime

from sqldaogenerator.entity.General import General
from sqldaogenerator.entity.Page import Page

"""This file is generated by sqldao-generator; don't modify anything. If you need to do it, you should create another class."""


@dataclass
class SampleCriterion(General, Page):
    col_datetime: datetime | str = None
    col_datetime_in: datetime | str = None
    col_datetime_start: datetime | str = None
    col_datetime_end: datetime | str = None
    col_double: float = None
    col_double_in: list[float] = None
    col_double_gte: float = None
    col_double_lte: float = None
    col_int: int = None
    col_int_in: list[int] = None
    col_int_gte: int = None
    col_int_lte: int = None
    col_text: str = None
    col_text_in: list[str] = None
    col_tinyint: int = None
    col_tinyint_in: list[int] = None
    col_tinyint_gte: int = None
    col_tinyint_lte: int = None
    col_var: str = None
    col_var_in: list[str] = None
